name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SOPS
      run: |
        SOPS_VERSION="3.8.1"
        curl -LO "https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64"
        sudo mv sops-v${SOPS_VERSION}.linux.amd64 /usr/local/bin/sops
        sudo chmod +x /usr/local/bin/sops
        sops --version
    
    - name: Install Age
      run: |
        AGE_VERSION="1.1.1"
        curl -LO "https://github.com/FiloSottile/age/releases/download/v${AGE_VERSION}/age-v${AGE_VERSION}-linux-amd64.tar.gz"
        tar -xzf age-v${AGE_VERSION}-linux-amd64.tar.gz
        sudo mv age/age* /usr/local/bin/
        age-keygen --version
    
    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
    
    - name: Run tests
      run: make test
    
    - name: Run linting
      run: make lint